version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - changelogithub
  - importantimport
  - masknet
  - minzipped
  - moeru
  - nomic
  - xsai
ignoreWords: []
import: []
